apiVersion: v1
kind: Service
metadata:
  name: mongo-service   # ⚡ 改名，避免跟 Pod 重名
  namespace: special-group
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
