apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: special-group
spec:
  type: NodePort   # ⚡ NodePort，但不指定 nodePort，交給 K8s 自動分配
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
